name: skillseeds
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Pacotes de produção...
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  flutter_markdown: ^0.6.18
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

  # --- ADICIONADOS PARA O SUPABASE ---
  supabase_flutter: ^2.5.0 # Pacote oficial do Supabase
  flutter_dotenv: ^5.1.0   # Para carregar as chaves do .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  # Assets...
  assets:
    - assets/images/app_icon.png
    - assets/policies/
    - .env # <-- ADICIONADO: Registra o .env como um asset